services:
  remna-bot:
    image: ghcr.io/case211/remna-ad:latest
    container_name: remna-telegram-bot-prod
    restart: unless-stopped
    env_file:
      - .env

    environment:
      # Только переменные, специфичные для production
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    
    volumes:
      # Mount logs directory for persistence
      - remna-bot-logs:/app/logs
      
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
      # Network configuration
    networks:
      - remnawave-network
    # Production logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # User specification (matches Dockerfile)
    user: "1000:1000"

volumes:
  remna-bot-logs:
    driver: local

networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge
    external: true